project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Katie Cheslick"
    left:
      - href: index.qmd
        text: Home
      - href: aboutme.qmd
        text: About me
      - about.qmd
      - href: myart.qmd
        text: Artwork
  page-footer:
    background: light 
    left: Copyright 2024, Katie Cheslick
    right: This website is built with RStudio and Quarto.
format:
  html:
    theme: styles.scss
    mainfont: Montserrat
    css: styles.css
    toc: true
    page-layout: full

editor: visual

