project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Katie Cheslick"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: myart.qmd
        text: Artwork

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    page-layout: full

editor: visual

