---
title: "Education"
---

During my time at UCSB, there were certain classes which I felt were extremely impactful, as they taught me important skills and knowledge, and influenced my career path. Some of these classes, as well as the way in which they influenced me, are listed below. I have also included some projects, created during my undergraduate education, which I am especially proud of.

## Key Courses

**Agroecology, taught by Liz Carlisle**

While I had heard about regenerative agriculture before this class, it was lectures in this course that really solidified my understanding about what regenerative farming techniques look like, why they are important, and how they can be integrated into our society. I was fascinated by techniques like temporal biodiversity of crop species (as a way to cycle nutrients and interrupt pest patterns), intercropping, hedgerows, and livestock integration; marveling at the ways in which our food systems can more closely mimic the natural ecosystem, and thrive as a result. It gave me hope to learn how much of our global carbon emissions is the result of the food sector, and farming practices specifically, because this is something that we have the knowledge and power to change.

**Soils of California, taught by Iriz Holzer**

This course, taken in my last year of college, allowed me to understand soil more deeply: what it is exactly, how it is made through weathering and other geologic processes, how and why soils vary by location, how they play a role in global carbon and nitrogen cycles, and how we can maintain the health of our soils. By participating in lab work in the field each week, I learned how to identify soil horizons, measure soil properties such as color, texture, consistence, and pH, and how to classify a soil. These skills have allowed me to think about the earth under our feet in a new way, and have helped to put knowledge about agriculture across the globe into perspective, as I can understand more about why certain crops are successful in some places but not others.

**Statistics for Environmental Studies, by An Bui**

Though I had taken statistics classes before, this class was unique in that it was combined with learning the programming language R. I learned important statistical tests and principles, which has allowed me to be a better scientist and analyze scientific papers in a more comprehensive way. I also learned how to create a variety of data visualizations to illustrate different types of data, and how to create a website and generative art (art made using code). This course pushed me outside of my comfort zone, and helped me to acquire skills that I will be taking forward in my daily life.

**Environmental Economics, by Robert Heilmayr**

This course provided a new lens for me, through which I could view environmental issues as part of a big picture—a picture of the world we live in, in which environmental health is governed by economic practices and economic opportunity. I learned how environmental issues cannot be separated from the capitalist system in which they exist, and how environmental issues which seem easy to fix at first glace are often complicated by the economic practices that drive them.

## Project Portfolio

**Studying Caenorhabditis elegans: Using RNAi to Knock Down UNC-3 and LPR-5 Genes to Determine Gene Necessity for Chemoperception**

{{< pdf C.elegansproject.pdf width=400 height=600 >}}

**Santa Barbara Conservation Efforts and Opportunities**

{{< pdf SBConsvOpportunities.pdf width=400 height=600 >}}

\
